export const description = {
  map: "Карта №121",
  title: "Назви для джерела (в колодязі, криниці і т.&nbsp;п.)",
  comment:
    "<p>Як називається джерело (струмінь підземної води, який витікає на поверхню землі \
    чи в криницю, колодязь і т.&nbsp;ін., отвір, яким виходить цей струмінь на поверхню): \
    <em>джерело, нора, булькіт, булькот, жила</em>..?</p> \
    <p> Для картографування взято назви для звичайного джерела, \
    яке буває в колодязі, криниці і т.&nbsp;п. \
    При складанні карти не враховані спеціальні назви для інших щодо характеру і т.&nbsp;д. витоків води з-під землі \
    (напр. <em>голова́н’а, голови́ц’а, морс’ке́ о́ко</em> (н.&nbsp;пп. 209, 210 та ін.), \
    <em>вôдôт’і́ч’, вôдôт’і́ш’</em> (н.&nbsp;п. 1), <em>вôдôту́к</em> (н.&nbsp;пп. 10, 12, 14, 28 та ін.) — \
    «великий витік води з-під землі, скелі, зокрема такий, який дає початок річки і т.&nbsp;п.»). \
    При картографуванні не враховане також <em>студни́ч’ка, стунни́ч’ка</em>, \
    яке дехто в н.&nbsp;пп. 29, 30, 62 пояснює і як «джерело»; \
    взагалі <em>студни́ч’ка, стунни́ч’ка</em> тут означає «криниця», «криничка», див. карту&nbsp;№&nbsp;3.</p>\
    <p>У селах західної частини досліджуваної території спеціальна назва для джерела часто відсутня, \
    називають його тут звичайно <em>жи́ла, жы́ла, жы́<sup>о</sup>ла</em>, тобто так само, \
    як і підземний канал, прохід, яким протікає струмінь води.</p>\
    <p>Знаком для <em>нора́</em> скартографовано у н.&nbsp;п. 74 <em>нора́</em> і <em>н’ура́</em>, \
    яке вживається окремими мовлянами. \
    Знаком для <em>бу́л’кот</em> скартографовано у н.&nbsp;п. 45 <em>бу́л’кот</em> і <em>бу́л’кет</em>. \
    Загальним відсильним знаком скартографовано у н.&nbsp;п. 35 <em>пра́ми<sup>е</sup>н</em> \
    (< словац. prameň — «джерело» та ін.); у н.&nbsp;п. 61 <em>фо́рашка</em> чи <em>фора́шка</em> \
    (< мадьяр. forráska — «джерело», «криничка»).</p>\
    <p>Відносно вживання картографованих назв автори відповідей зауважили, \
    що у н.&nbsp;пп. 8, 15, 29–31, 62 <em>жерело́</em> вживається переважно на означення джерела, \
    від якого бере початок потічок, хоч нерідко виступає і як назва звичайного джерела. \
    У н.&nbsp;пп. 43, 67, 72 <em>жерело́</em> вживає лише частина мовлян, \
    дехто його вважає новим словом, що поширилося від впливом літературної мови.</p>\
    <p>Слово <em>жи́ла, жы́ла, жы́<sup>о</sup>ла</em> широко відоме і в ареалах \
    <em>нора́, бу́л’кіт, бу́л’кот</em>, але із значенням «підземний канал, прохід, яким протікає підземний струмінь води».</p>\
    <p><em>Пуста́ тота́ нора́, з йако́йі не<sup>и</sup> все нори́т вода́</em> (н.&nbsp;п.&nbsp;201).<br>\
    <em>Не<sup>и</sup> с ко́ждойі нори́ чи́ста вода́ нори́т</em> (н.&nbsp;п.&nbsp;201).<br>\
    <em>По вели́ких дождж’а́х вели́кі но́ри йгра́йут</em> (н.&nbsp;п.&nbsp;210).<br>\
    <em>Не<sup>и</sup>ма́ гори́ без нори́, а чолові́ка без жури́</em> (н.&nbsp;п.&nbsp;209).<br>\
    <em>Су́нутс’а л’іса́ згоры́, ги во́ды з норы́</em> (н.&nbsp;п.&nbsp;196).</p>",
};

export const legend = {
  black: "жерело́",
  white: "нора́ (н’ура́)",
  xlines: "бу́л’кіт",
  xlinesH: "бу́л’кот (бу́л’кет)",
  hlines: "жи́ла, жы́ла, жы́ᵒла",
  cross: "поодинокі назви з іншими коренями",
};

export const pointdata = {
  1: "hlines xlinesH",
  2: "xlinesH",
  3: "white",
  4: "white",
  5: "black-mini hlines",
  6: "black-mini hlines",
  7: "hlines",
  8: "black hlines comment",
  9: "hlines",
  10: "hlines",
  11: "black hlines",
  12: "hlines",
  13: "black hlines",
  14: "hlines",
  15: "black-mini hlines comment",
  16: "white",
  17: "white",
  18: "xlinesH",
  19: "xlinesH",
  20: "xlinesH",
  21: "white",
  22: "xlinesH",
  23: "xlinesH",
  24: "xlinesH",
  25: "black-mini hlines",
  26: "black-mini hlines",
  27: "black hlines",
  28: "black hlines",
  29: "black hlines comment",
  30: "black hlines comment",
  31: "black-mini hlines comment",
  32: "black hlines",
  33: "hlines",
  34: "black-mini hlines",
  35: "hlines cross",
  36: "black",
  37: "hlines",
  38: "hlines",
  39: "hlines",
  40: "white",
  41: "hlines",
  42: "white",
  43: "black-mini hlines-mini white comment",
  44: "xlinesH",
  45: "xlinesH comment",
  46: "xlines",
  47: "white",
  48: "white",
  49: "xlines",
  50: "xlines",
  51: "xlines",
  52: "xlines",
  53: "xlines",
  54: "white",
  55: "white",
  56: "white",
  57: "white",
  58: "white",
  59: "white",
  60: "white",
  61: "hlines cross",
  62: "black hlines comment",
  63: "hlines",
  64: "hlines",
  65: "black hlines",
  66: "hlines",
  67: "black-mini hlines comment",
  68: "hlines",
  69: "hlines",
  70: "hlines",
  71: "white",
  72: "black hlines comment",
  73: "white",
  74: "white comment",
  75: "white",
  76: "white",
  77: "white",
  78: "white",
  79: "white",
  80: "white",
  81: "white",
  82: "white",
  83: "white",
  84: "white",
  85: "white",
  86: "white",
  87: "black white-mini",
  88: "white",
  89: "white",
  90: "white",
  91: "white",
  92: "white",
  93: "white",
  94: "white",
  95: "white",
  96: "white",
  97: "white",
  98: "white",
  99: "white",
  100: "white",
  101: "white",
  102: "white",
  103: "white",
  104: "white",
  105: "white",
  106: "white",
  107: "white",
  108: "white",
  109: "white",
  110: "white",
  111: "white",
  112: "white",
  113: "white",
  114: "white",
  115: "white",
  116: "white",
  117: "white",
  118: "white",
  119: "white",
  120: "white",
  121: "white",
  122: "white",
  123: "white",
  124: "white",
  125: "white",
  126: "white",
  127: "white",
  128: "white",
  129: "white",
  130: "white",
  131: "white",
  132: "white",
  133: "white",
  134: "white",
  135: "white",
  136: "white",
  137: "white",
  138: "white",
  139: "white",
  140: "white",
  141: "white",
  142: "white",
  143: "white",
  144: "white",
  145: "white",
  146: "white",
  147: "white",
  148: "white",
  149: "white",
  150: "white",
  151: "white",
  152: "white",
  153: "white",
  154: "white",
  155: "white",
  156: "white",
  157: "white",
  158: "white",
  159: "white",
  160: "white",
  161: "white",
  162: "white",
  163: "white",
  164: "white",
  165: "white",
  166: "white",
  167: "white",
  168: "white",
  169: "white",
  170: "white",
  171: "white",
  172: "white",
  173: "white",
  174: "white",
  175: "white",
  176: "white",
  177: "white",
  178: "white",
  179: "white",
  180: "white",
  181: "white",
  182: "white",
  183: "white",
  184: "white",
  185: "white",
  186: "white",
  187: "white",
  188: "white",
  189: "white",
  190: "white",
  191: "white",
  192: "white",
  193: "white",
  194: "white",
  195: "white",
  196: "white",
  197: "white",
  198: "white",
  199: "white",
  200: "white",
  201: "white",
  202: "white",
  203: "white",
  204: "white",
  205: "white",
  206: "white",
  207: "white",
  208: "white",
  209: "white",
  210: "white",
  211: "white",
  212: "white",
};

export const pointcomment = {};

export const linedata = { present: false };
